const char striphtml_xsl[] =
  "<?xml version='1.0'?>\n"
  "<xsl:stylesheet xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"\n"
  "                version='1.0'>\n"
  "\n"
  "<xsl:output method=\"html\"/>\n"
  "\n"
  "<xsl:template match=\"/\">\n"
  "  <div>\n"
  "  <xsl:apply-templates/>\n"
  " </div>\n"
  "</xsl:template>\n"
  "\n"
  "<!-- This template lets safe elements through -->\n"
  "<!-- The list of elements in the match attribute isn't complete -->\n"
  "<xsl:template match=\"h1|h2|h3|h4|h5|h6|p|a|div|ul|li|ol|table|tr|td|br\">\n"
  "  <xsl:element name=\"{name(.)}\">\n"
  "    <xsl:copy-of select=\"@*\"/>\n"
  "    <xsl:apply-templates/>\n"
  "  </xsl:element>\n"
  "</xsl:template>\n"
  "\n"
  "<!-- stripping template.  \"eat\" unwanted tags and their content -->\n"
  "<!-- The list of elements in the match attribute isn't complete -->\n"
  "<xsl:template match=\"head|script|object|form|img|applet\"/>\n"
  "\n"
  "<!-- Anything not matched by either of the above templates -->\n"
  "<!-- will get its CDATA content output -->\n"
  "\n"
  "</xsl:stylesheet>\n"
;
